<?php


namespace app\index\controller;


class Tag extends Base
{
    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function d() {

    }
}